INSERT INTO COMPANY (COMPANY_ID, NAME) VALUES (1, '원티드랩');
INSERT INTO COMPANY (COMPANY_ID, NAME) VALUES (2, '외국회사');

INSERT INTO RECRUITMENT (RECRUITMENT_ID, COMPANY_ID, COUNTRY, REGION, POSITION, REWARD, TECH_STACK, DETAIL)
VALUES (1, 1, '한국', '서울', '백엔드', '1500000', 'Python', '원티드랩에서 백엔드 주니어 개발자를 ''적극'' 채용합니다. 자격요건은..');

INSERT INTO RECRUITMENT (RECRUITMENT_ID, COMPANY_ID, COUNTRY, REGION, POSITION, REWARD, TECH_STACK, DETAIL)
VALUES (2, 2, '일본', '도쿄', '프론트엔드', '100', 'Java', '도쿄에서 프론트엔드 시니어 개발자를 채용합니다.');